In [162]:
import pandas as pd

In [163]:
df = pd.read_csv("matches.csv", index_col = 0)

In [164]:
df.head()

,date,all_comps/shooting_time,all_comps/shooting_comp,all_comps/shooting_round,all_comps/shooting_day,all_comps/shooting_venue,all_comps/shooting_result,all_comps/shooting_gf,all_comps/shooting_ga,all_comps/shooting_opponent,...,all_comps/possession_notes,all_comps/possession_touches,all_comps/possession_def pen,all_comps/possession_def 3rd,all_comps/possession_mid 3rd,all_comps/possession_att 3rd,all_comps/possession_att pen,all_comps/possession_live,all_comps/possession_season,all_comps/possession_team
0,2023-08-06,16:00,Community Shield,FA Community Shield,Sun,Neutral,D,1 (1),1 (4),Arsenal,...,Arsenal won on penalty kicks following normal ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-20182017-2018,Manchester City
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,NaN,835.0,75.0,267.0,412.0,158.0,23.0,835.0,2017-20182017-2018,Manchester City
2,2023-08-16,22:00,Super Cup,UEFA Super Cup,Wed,Home,D,1 (5),1 (4),es Sevilla,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-20182017-2018,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,NaN,788.0,65.0,212.0,411.0,174.0,21.0,788.0,2017-20182017-2018,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,NaN,893.0,40.0,153.0,440.0,304.0,53.0,892.0,2017-20182017-2018,Manchester City

In [165]:
import numpy as np
array = (df.columns.to_numpy())
print(array)

['date' 'all_comps/shooting_time' 'all_comps/shooting_comp'
 'all_comps/shooting_round' 'all_comps/shooting_day'
 'all_comps/shooting_venue' 'all_comps/shooting_result'
 'all_comps/shooting_gf' 'all_comps/shooting_ga'
 'all_comps/shooting_opponent' 'all_comps/shooting_xg'
 'all_comps/shooting_xga' 'all_comps/shooting_poss'
 'all_comps/shooting_attendance' 'all_comps/shooting_captain'
 'all_comps/shooting_formation' 'all_comps/shooting_referee'
 'all_comps/shooting_match report' 'all_comps/shooting_notes'
 'all_comps/shooting_sh' 'all_comps/shooting_sot'
 'all_comps/shooting_dist' 'all_comps/shooting_fk' 'all_comps/shooting_pk'
 'all_comps/shooting_pkatt' 'all_comps/shooting_season'
 'all_comps/shooting_team' 'date.1' 'all_comps/keeper_time'
 'all_comps/keeper_comp' 'all_comps/keeper_round' 'all_comps/keeper_day'
 'all_comps/keeper_venue' 'all_comps/keeper_result' 'all_comps/keeper_gf'
 'all_comps/keeper_ga' 'all_comps/keeper_opponent' 'all_comps/keeper_xg'
 'all_comps/keeper_xga' 'all_comps/keeper_poss'
 'all_comps/keeper_attendance' 'all_comps/keeper_captain'
 'all_comps/keeper_formation' 'all_comps/keeper_referee'
 'all_comps/keeper_match report' 'all_comps/keeper_notes'
 'all_comps/keeper_saves' 'all_comps/keeper_save%' 'all_comps/keeper_cs'
 'all_comps/keeper_pkatt' 'all_comps/keeper_pka' 'all_comps/keeper_pksv'
 'all_comps/keeper_pkm' 'all_comps/keeper_season' 'all_comps/keeper_team'
 'date.2' 'all_comps/passing_time' 'all_comps/passing_comp'
 'all_comps/passing_round' 'all_comps/passing_day'
 'all_comps/passing_venue' 'all_comps/passing_result'
 'all_comps/passing_gf' 'all_comps/passing_ga'
 'all_comps/passing_opponent' 'all_comps/passing_xg'
 'all_comps/passing_xga' 'all_comps/passing_poss'
 'all_comps/passing_attendance' 'all_comps/passing_captain'
 'all_comps/passing_formation' 'all_comps/passing_referee'
 'all_comps/passing_match report' 'all_comps/passing_notes'
 'all_comps/passing_cmp' 'all_comps/passing_cmp.1'
 'all_comps/passing_cmp.2' 'all_comps/passing_cmp.3'
 'all_comps/passing_att' 'all_comps/passing_att.1'
 'all_comps/passing_att.2' 'all_comps/passing_att.3'
 'all_comps/passing_cmp%' 'all_comps/passing_cmp%.1'
 'all_comps/passing_cmp%.2' 'all_comps/passing_cmp%.3'
 'all_comps/passing_totdist' 'all_comps/passing_prgdist'
 'all_comps/passing_season' 'all_comps/passing_team' 'date.3'
 'all_comps/possession_time' 'all_comps/possession_comp'
 'all_comps/possession_round' 'all_comps/possession_day'
 'all_comps/possession_venue' 'all_comps/possession_result'
 'all_comps/possession_gf' 'all_comps/possession_ga'
 'all_comps/possession_opponent' 'all_comps/possession_xg'
 'all_comps/possession_xga' 'all_comps/possession_poss'
 'all_comps/possession_attendance' 'all_comps/possession_captain'
 'all_comps/possession_formation' 'all_comps/possession_referee'
 'all_comps/possession_match report' 'all_comps/possession_notes'
 'all_comps/possession_touches' 'all_comps/possession_def pen'
 'all_comps/possession_def 3rd' 'all_comps/possession_mid 3rd'
 'all_comps/possession_att 3rd' 'all_comps/possession_att pen'
 'all_comps/possession_live' 'all_comps/possession_season'
 'all_comps/possession_team']

In [166]:
# Create the shooting dataframe
shooting_columns = ['date'] + [col for col in df.columns if col.startswith('all_comps/shooting_')]
shooting_df = df[shooting_columns]
shooting_df.columns = shooting_df.columns.str.replace('all_comps/shooting_', '')

# Create the keeper dataframe
keeper_columns = ['date.1'] + [col for col in df.columns if col.startswith('all_comps/keeper_')]
keeper_df = df[keeper_columns]
keeper_df.columns = keeper_df.columns.str.replace('all_comps/keeper_', '')
keeper_df.rename(columns={'date.1': 'date'}, inplace=True)

# Create the passing dataframe
passing_columns = ['date.2'] + [col for col in df.columns if col.startswith('all_comps/passing_')]
passing_df = df[passing_columns]
passing_df.columns = passing_df.columns.str.replace('all_comps/passing_', '')
passing_df.rename(columns={'date.2': 'date'}, inplace=True)

# Create the possession dataframe
possession_columns = ['date.3'] + [col for col in df.columns if col.startswith('all_comps/possession_')]
possession_df = df[possession_columns]
possession_df.columns = possession_df.columns.str.replace('all_comps/possession_', '')
possession_df.rename(columns={'date.3': 'date'}, inplace=True)

shooting_df = shooting_df[shooting_df['comp']=="Premier League"]
keeper_df = keeper_df[keeper_df['comp']=="Premier League"]
passing_df = passing_df[passing_df['comp']=="Premier League"]
possession_df = possession_df[possession_df['comp']=="Premier League"]

C:\Users\bruno\AppData\Local\Temp\ipykernel_10388\2370731479.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  keeper_df.rename(columns={'date.1': 'date'}, inplace=True)
C:\Users\bruno\AppData\Local\Temp\ipykernel_10388\2370731479.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  passing_df.rename(columns={'date.2': 'date'}, inplace=True)
C:\Users\bruno\AppData\Local\Temp\ipykernel_10388\2370731479.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  possession_df.rename(columns={'date.3': 'date'}, inplace=True)

In [167]:
shooting_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,Match Report,NaN,17.0,8.0,13.9,0.0,0.0,0.0,2017-20182017-2018,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,17.9,0.0,0.0,0.0,2017-20182017-2018,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,Match Report,NaN,29.0,9.0,17.3,2.0,0.0,1.0,2017-20182017-2018,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,Match Report,NaN,6.0,4.0,14.8,0.0,1.0,1.0,2017-20182017-2018,Manchester City
6,2023-08-13,14:00,Premier League,Matchweek 1,Sun,Away,D,2,2,Brentford,...,Match Report,NaN,18.0,6.0,19.6,0.0,0.0,0.0,2017-20182017-2018,Tottenham Hotspur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4863,2019-04-13,12:30,Premier League,Matchweek 34,Sat,Away,L,0,4,Tottenham,...,Match Report,NaN,7.0,1.0,18.9,1.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4864,2019-04-20,15:00,Premier League,Matchweek 35,Sat,Home,L,1,2,Watford,...,Match Report,NaN,13.0,3.0,18.1,1.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4865,2019-04-26,20:00,Premier League,Matchweek 36,Fri,Away,L,0,5,Liverpool,...,Match Report,NaN,5.0,1.0,21.6,0.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4866,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Manchester Utd,...,Match Report,NaN,7.0,3.0,19.0,1.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4867,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,D,1,1,Southampton,...,Match Report,NaN,10.0,3.0,22.2,0.0,0.0,0.0,2017-20182017-2018,Huddersfield Town

In [168]:
shooting_df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'sh', 'sot', 'dist', 'fk', 'pk',
       'pkatt', 'season', 'team'],
      dtype='object')

In [169]:
keeper_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,saves,save%,cs,pkatt,pka,pksv,pkm,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,NaN,1.0,100.0,1.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,NaN,1.0,100.0,1.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,NaN,3.0,75.0,0.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Manchester City
6,2023-08-13,14:00,Premier League,Matchweek 1,Sun,Away,D,2,2,Brentford,...,NaN,4.0,83.3,0.0,1.0,1.0,0.0,0.0,2017-20182017-2018,Tottenham Hotspur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4863,2019-04-13,12:30,Premier League,Matchweek 34,Sat,Away,L,0,4,Tottenham,...,NaN,1.0,20.0,0.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4864,2019-04-20,15:00,Premier League,Matchweek 35,Sat,Home,L,1,2,Watford,...,NaN,4.0,66.7,0.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4865,2019-04-26,20:00,Premier League,Matchweek 36,Fri,Away,L,0,5,Liverpool,...,NaN,2.0,28.6,0.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4866,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Manchester Utd,...,NaN,6.0,85.7,0.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Huddersfield Town
4867,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,D,1,1,Southampton,...,NaN,2.0,66.7,0.0,0.0,0.0,0.0,0.0,2017-20182017-2018,Huddersfield Town

In [170]:
keeper_df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'saves', 'save%', 'cs', 'pkatt',
       'pka', 'pksv', 'pkm', 'season', 'team'],
      dtype='object')

In [171]:
passing_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,att.2,att.3,cmp%,cmp%.1,cmp%.2,cmp%.3,totdist,prgdist,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,277.0,84.0,88.5,95.9,91.0,60.7,10790.0,3194.0,2017-20182017-2018,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,263.0,58.0,88.5,93.7,89.0,65.5,10155.0,2989.0,2017-20182017-2018,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,352.0,81.0,89.2,95.4,92.6,67.9,12243.0,3342.0,2017-20182017-2018,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,311.0,90.0,88.9,92.7,92.6,72.2,11763.0,3078.0,2017-20182017-2018,Manchester City
6,2023-08-13,14:00,Premier League,Matchweek 1,Sun,Away,D,2,2,Brentford,...,242.0,42.0,87.3,94.8,88.4,40.5,9253.0,2521.0,2017-20182017-2018,Tottenham Hotspur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4863,2019-04-13,12:30,Premier League,Matchweek 34,Sat,Away,L,0,4,Tottenham,...,88.0,76.0,70.9,87.8,76.1,44.7,4111.0,1648.0,2017-20182017-2018,Huddersfield Town
4864,2019-04-20,15:00,Premier League,Matchweek 35,Sat,Home,L,1,2,Watford,...,122.0,65.0,79.2,90.4,78.7,64.6,5551.0,2215.0,2017-20182017-2018,Huddersfield Town
4865,2019-04-26,20:00,Premier League,Matchweek 36,Fri,Away,L,0,5,Liverpool,...,100.0,64.0,67.4,79.0,80.0,37.5,3854.0,1863.0,2017-20182017-2018,Huddersfield Town
4866,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Manchester Utd,...,114.0,64.0,68.9,82.1,72.8,37.5,4249.0,2100.0,2017-20182017-2018,Huddersfield Town
4867,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,D,1,1,Southampton,...,108.0,89.0,65.2,80.1,67.6,38.2,4611.0,1770.0,2017-20182017-2018,Huddersfield Town

In [172]:
passing_df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'cmp', 'cmp.1', 'cmp.2', 'cmp.3',
       'att', 'att.1', 'att.2', 'att.3', 'cmp%', 'cmp%.1', 'cmp%.2', 'cmp%.3',
       'totdist', 'prgdist', 'season', 'team'],
      dtype='object')

In [173]:
possession_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,touches,def pen,def 3rd,mid 3rd,att 3rd,att pen,live,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,NaN,835.0,75.0,267.0,412.0,158.0,23.0,835.0,2017-20182017-2018,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,NaN,788.0,65.0,212.0,411.0,174.0,21.0,788.0,2017-20182017-2018,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,NaN,893.0,40.0,153.0,440.0,304.0,53.0,892.0,2017-20182017-2018,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,NaN,838.0,64.0,222.0,483.0,138.0,20.0,837.0,2017-20182017-2018,Manchester City
6,2023-08-13,14:00,Premier League,Matchweek 1,Sun,Away,D,2,2,Brentford,...,NaN,864.0,63.0,154.0,375.0,345.0,32.0,864.0,2017-20182017-2018,Tottenham Hotspur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4863,2019-04-13,12:30,Premier League,Matchweek 34,Sat,Away,L,0,4,Tottenham,...,NaN,442.0,54.0,144.0,215.0,89.0,15.0,442.0,2017-20182017-2018,Huddersfield Town
4864,2019-04-20,15:00,Premier League,Matchweek 35,Sat,Home,L,1,2,Watford,...,NaN,529.0,50.0,143.0,266.0,126.0,12.0,529.0,2017-20182017-2018,Huddersfield Town
4865,2019-04-26,20:00,Premier League,Matchweek 36,Fri,Away,L,0,5,Liverpool,...,NaN,450.0,54.0,164.0,199.0,91.0,10.0,450.0,2017-20182017-2018,Huddersfield Town
4866,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Manchester Utd,...,NaN,476.0,68.0,173.0,191.0,118.0,13.0,476.0,2017-20182017-2018,Huddersfield Town
4867,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,D,1,1,Southampton,...,NaN,543.0,63.0,207.0,225.0,116.0,7.0,543.0,2017-20182017-2018,Huddersfield Town

In [174]:
possession_df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'touches', 'def pen', 'def 3rd',
       'mid 3rd', 'att 3rd', 'att pen', 'live', 'season', 'team'],
      dtype='object')

In [175]:
# Merge the dataframes using the "date" column as the key
merged_df = shooting_df.merge(keeper_df, on=['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga', 'opponent', 'xg', 'xga', 'poss', 'pkatt', 'attendance', 'captain', 'formation', 'referee', 'match report', 'notes', 'season', 'team']) \
    .merge(passing_df, on=['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga', 'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation', 'referee', 'match report', 'notes', 'season', 'team']) \
    .merge(possession_df, on=['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga', 'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation', 'referee', 'match report', 'notes', 'season', 'team'])


# If you want to reset the index of the merged dataframe
merged_df.reset_index(drop=True, inplace=True)

In [176]:
merged_df = merged_df[merged_df["comp"] == "Premier League"]
merged_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,cmp%.3,totdist,prgdist,touches,def pen,def 3rd,mid 3rd,att 3rd,att pen,live
0,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,60.7,10790.0,3194.0,835.0,75.0,267.0,412.0,158.0,23.0,835.0
1,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,65.5,10155.0,2989.0,788.0,65.0,212.0,411.0,174.0,21.0,788.0
2,2023-08-19,17:30,Premier League,Matchweek 2,Sat,Home,W,2,0,Manchester Utd,...,66.1,7812.0,2826.0,675.0,107.0,284.0,232.0,165.0,37.0,675.0
3,2023-08-26,12:30,Premier League,Matchweek 3,Sat,Away,W,2,0,Bournemouth,...,59.2,8012.0,3260.0,698.0,84.0,255.0,265.0,185.0,43.0,698.0
4,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Away,W,5,2,Burnley,...,56.9,7886.0,2647.0,720.0,105.0,250.0,298.0,179.0,50.0,720.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,2019-04-13,12:30,Premier League,Matchweek 34,Sat,Away,L,0,4,Tottenham,...,44.7,4111.0,1648.0,442.0,54.0,144.0,215.0,89.0,15.0,442.0
3004,2019-04-20,15:00,Premier League,Matchweek 35,Sat,Home,L,1,2,Watford,...,64.6,5551.0,2215.0,529.0,50.0,143.0,266.0,126.0,12.0,529.0
3005,2019-04-26,20:00,Premier League,Matchweek 36,Fri,Away,L,0,5,Liverpool,...,37.5,3854.0,1863.0,450.0,54.0,164.0,199.0,91.0,10.0,450.0
3006,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Manchester Utd,...,37.5,4249.0,2100.0,476.0,68.0,173.0,191.0,118.0,13.0,476.0
3007,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,D,1,1,Southampton,...,38.2,4611.0,1770.0,543.0,63.0,207.0,225.0,116.0,7.0,543.0

In [177]:
merged_df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'sh', 'sot', 'dist', 'fk', 'pk',
       'pkatt', 'season', 'team', 'saves', 'save%', 'cs', 'pka', 'pksv', 'pkm',
       'cmp', 'cmp.1', 'cmp.2', 'cmp.3', 'att', 'att.1', 'att.2', 'att.3',
       'cmp%', 'cmp%.1', 'cmp%.2', 'cmp%.3', 'totdist', 'prgdist', 'touches',
       'def pen', 'def 3rd', 'mid 3rd', 'att 3rd', 'att pen', 'live'],
      dtype='object')

In [178]:
merged_df['season'] = merged_df['season'].str[14:]

In [179]:
merged_df.season

0       2018
1       2018
2       2018
3       2018
4       2018
        ...
3003    2018
3004    2018
3005    2018
3006    2018
3007    2018
Name: season, Length: 3008, dtype: object

In [180]:
merged_df.shape

(3008, 54)

In [181]:
merged_df["team"].value_counts()

Wolverhampton Wanderers     159
Liverpool                   157
Everton                     156
Newcastle United            155
Arsenal                     154
Southampton                 153
Brighton and Hove Albion    152
Chelsea                     151
Tottenham Hotspur           151
Crystal Palace              150
West Ham United             144
Manchester United           143
Leicester City              138
Manchester City             138
Burnley                     130
Aston Villa                 118
Bournemouth                  92
Leeds United                 90
Watford                      85
Fulham                       83
Sheffield United             69
Brentford                    59
Norwich City                 55
Nottingham Forest            33
Huddersfield Town            31
West Bromwich Albion         30
Cardiff City                 29
Luton Town                    3
Name: team, dtype: int64

In [182]:
merged_df["round"].value_counts()

Matchweek 4     102
Matchweek 1      90
Matchweek 33     88
Matchweek 21     88
Matchweek 17     86
Matchweek 36     86
Matchweek 3      84
Matchweek 23     84
Matchweek 15     84
Matchweek 5      82
Matchweek 8      82
Matchweek 12     82
Matchweek 30     80
Matchweek 37     80
Matchweek 9      80
Matchweek 13     78
Matchweek 6      78
Matchweek 35     78
Matchweek 2      78
Matchweek 34     78
Matchweek 31     78
Matchweek 11     78
Matchweek 20     76
Matchweek 27     76
Matchweek 14     76
Matchweek 32     76
Matchweek 28     76
Matchweek 24     76
Matchweek 7      75
Matchweek 22     75
Matchweek 16     74
Matchweek 29     74
Matchweek 26     74
Matchweek 25     74
Matchweek 18     72
Matchweek 10     72
Matchweek 19     70
Matchweek 38     68
Name: round, dtype: int64

In [183]:
merged_df.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf               object
ga               object
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes            object
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season           object
team             object
saves           float64
save%           float64
cs              float64
pka             float64
pksv            float64
pkm             float64
cmp             float64
cmp.1           float64
cmp.2           float64
cmp.3           float64
att             float64
att.1           float64
att.2           float64
att.3           float64
cmp%            float64
cmp%.1          float64
cmp%.2          float64
cmp%.3          float64
totdist         float64
prgdist         float64
touches         float64
def pen         float64
def 3rd         float64
mid 3rd         float64
att 3rd         float64
att pen         float64
live            float64
dtype: object

In [184]:
merged_df["date"] = pd.to_datetime(df["date"])

In [185]:
merged_df["venue_code"] = merged_df["venue"].astype("category").cat.codes

In [186]:
merged_df["opp_code"] = merged_df["opponent"].astype("category").cat.codes

In [187]:
merged_df["hour"] = merged_df["time"].str.replace(":.+", "", regex = True).astype("int")

In [188]:
merged_df["day_code"] = merged_df["date"].dt.dayofweek

In [189]:
merged_df["target"] = (merged_df["result"] == "W").astype("int")

In [190]:
merged_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,def 3rd,mid 3rd,att 3rd,att pen,live,venue_code,opp_code,hour,day_code,target
0,2023-08-06,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,267.0,412.0,158.0,23.0,835.0,0,5,20,6,1
1,2023-08-11,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,212.0,411.0,174.0,21.0,788.0,1,18,20,4,1
2,2023-08-16,17:30,Premier League,Matchweek 2,Sat,Home,W,2,0,Manchester Utd,...,284.0,232.0,165.0,37.0,675.0,1,17,17,2,1
3,2023-08-19,12:30,Premier League,Matchweek 3,Sat,Away,W,2,0,Bournemouth,...,255.0,265.0,185.0,43.0,698.0,0,2,12,5,1
4,2023-08-27,15:00,Premier League,Matchweek 4,Sat,Away,W,5,2,Burnley,...,250.0,298.0,179.0,50.0,720.0,0,5,15,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,2020-03-11,12:30,Premier League,Matchweek 34,Sat,Away,L,0,4,Tottenham,...,144.0,215.0,89.0,15.0,442.0,0,23,12,2,0
3004,2020-06-21,15:00,Premier League,Matchweek 35,Sat,Home,L,1,2,Watford,...,143.0,266.0,126.0,12.0,529.0,1,24,15,6,0
3005,2020-06-24,20:00,Premier League,Matchweek 36,Fri,Away,L,0,5,Liverpool,...,164.0,199.0,91.0,10.0,450.0,0,14,20,2,0
3006,2020-07-02,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Manchester Utd,...,173.0,191.0,118.0,13.0,476.0,1,17,14,3,0
3007,2020-07-05,15:00,Premier League,Matchweek 38,Sun,Away,D,1,1,Southampton,...,207.0,225.0,116.0,7.0,543.0,0,22,15,6,0

In [191]:
encoded_formations = pd.get_dummies(merged_df['formation'], prefix='formation')

# Step 2: Feature Engineering (optional)
# For example, you can calculate the number of defenders, midfielders, and forwards in the formation
def count_positions(formation):
    try:
        positions = formation.split('-')
        return {
            'defenders': int(positions[0]),
            'midfielders': int(positions[1]),
            'forwards': int(positions[-1])
        }
    except (ValueError, IndexError):
        # Handle invalid formation strings or missing values here
        return {
            'defenders': 0,
            'midfielders': 0,
            'forwards': 0
        }

merged_df['num_defenders'] = merged_df['formation'].apply(lambda x: count_positions(x)['defenders'])
merged_df['num_midfielders'] = merged_df['formation'].apply(lambda x: count_positions(x)['midfielders'])
merged_df['num_forwards'] = merged_df['formation'].apply(lambda x: count_positions(x)['forwards'])

# Step 3: Concatenate the one-hot encoded formations with the original dataframe
merged_df = pd.concat([merged_df, encoded_formations], axis=1)

In [192]:
grouped_matches = merged_df.groupby("team")

In [193]:
group = grouped_matches.get_group("Manchester City")

In [194]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,formation_4-2-2-2,formation_4-2-3-1,formation_4-3-1-2,formation_4-3-2-1,formation_4-3-3,formation_4-4-1-1,formation_4-4-2,formation_4-5-1,formation_5-3-2,formation_5-4-1
0,2023-08-06,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0,1,0,0,0,0,0,0,0,0
1,2023-08-11,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0,1,0,0,0,0,0,0,0,0
60,2023-08-26,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,0,1,0,0,0,0,0,0,0,0
61,2023-08-29,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,0,0,0,0,1,0,0,0,0,0
62,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,2021-02-21,12:30,Premier League,Matchweek 35,Sat,Home,W,1,0,Tottenham,...,0,0,0,0,1,0,0,0,0,0
2426,2021-02-25,20:00,Premier League,Matchweek 31,Wed,Away,W,2,0,Manchester Utd,...,0,0,0,0,1,0,0,0,0,0
2427,2021-02-28,14:05,Premier League,Matchweek 36,Sun,Away,W,1,0,Burnley,...,0,0,0,0,1,0,0,0,0,0
2428,2021-03-06,20:00,Premier League,Matchweek 37,Mon,Home,W,1,0,Leicester City,...,0,0,0,0,1,0,0,0,0,0
2429,2021-03-11,15:00,Premier League,Matchweek 38,Sun,Away,W,4,1,Brighton,...,0,0,0,0,0,1,0,0,0,0

In [200]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    for i in range(len(cols)):
        group[new_cols[i]] = rolling_stats.iloc[:, i]
    group = group.dropna(subset=new_cols)
    return group

In [201]:
merged_df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'sh', 'sot', 'dist', 'fk', 'pk',
       'pkatt', 'season', 'team', 'saves', 'save%', 'cs', 'pka', 'pksv', 'pkm',
       'cmp', 'cmp.1', 'cmp.2', 'cmp.3', 'att', 'att.1', 'att.2', 'att.3',
       'cmp%', 'cmp%.1', 'cmp%.2', 'cmp%.3', 'totdist', 'prgdist', 'touches',
       'def pen', 'def 3rd', 'mid 3rd', 'att 3rd', 'att pen', 'live',
       'venue_code', 'opp_code', 'hour', 'day_code', 'target', 'num_defenders',
       'num_midfielders', 'num_forwards', 'formation_3-1-4-2',
       'formation_3-2-4-1', 'formation_3-3-3-1', 'formation_3-4-1-2',
       'formation_3-4-3', 'formation_3-4-3â—†', 'formation_3-5-1-1',
       'formation_3-5-2', 'formation_4-1-2-1-2â—†', 'formation_4-1-3-2',
       'formation_4-1-4-1', 'formation_4-2-2-2', 'formation_4-2-3-1',
       'formation_4-3-1-2', 'formation_4-3-2-1', 'formation_4-3-3',
       'formation_4-4-1-1', 'formation_4-4-2', 'formation_4-5-1',
       'formation_5-3-2', 'formation_5-4-1'],
      dtype='object')

In [202]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt", "xg", "xga", "poss", 'num_defenders',
       'num_midfielders', 'num_forwards', 'def pen', 'def 3rd', 'mid 3rd', 'att 3rd', 'att pen',
       'saves', 'save%', 'cs', 'pka', 'pksv', 'pkm',
       'cmp', 'cmp.1', 'cmp.2', 'cmp.3', 'att', 'att.1', 'att.2', 'att.3',
       'cmp%', 'cmp%.1', 'cmp%.2', 'cmp%.3', 'totdist', 'prgdist', 'touches',
       'def pen', 'def 3rd', 'mid 3rd', 'att 3rd', 'att pen']
new_cols = [f"{c}_rolling" for c in cols]

In [203]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling',
 'xg_rolling',
 'xga_rolling',
 'poss_rolling',
 'num_defenders_rolling',
 'num_midfielders_rolling',
 'num_forwards_rolling',
 'def pen_rolling',
 'def 3rd_rolling',
 'mid 3rd_rolling',
 'att 3rd_rolling',
 'att pen_rolling',
 'saves_rolling',
 'save%_rolling',
 'cs_rolling',
 'pka_rolling',
 'pksv_rolling',
 'pkm_rolling',
 'cmp_rolling',
 'cmp.1_rolling',
 'cmp.2_rolling',
 'cmp.3_rolling',
 'att_rolling',
 'att.1_rolling',
 'att.2_rolling',
 'att.3_rolling',
 'cmp%_rolling',
 'cmp%.1_rolling',
 'cmp%.2_rolling',
 'cmp%.3_rolling',
 'totdist_rolling',
 'prgdist_rolling',
 'touches_rolling',
 'def pen_rolling',
 'def 3rd_rolling',
 'mid 3rd_rolling',
 'att 3rd_rolling',
 'att pen_rolling']

In [204]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,att.1_rolling,att.2_rolling,att.3_rolling,cmp%_rolling,cmp%.1_rolling,cmp%.2_rolling,cmp%.3_rolling,totdist_rolling,prgdist_rolling,touches_rolling
2403,2020-11-26,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Newcastle Utd,...,309.333333,256.333333,76.000000,86.266667,92.700000,90.333333,66.500000,9725.333333,2952.666667,802.666667
2404,2020-11-29,15:00,Premier League,Matchweek 5,Sat,Home,W,3,0,Fulham,...,352.333333,279.000000,74.000000,88.400000,93.100000,91.466667,73.433333,10783.666667,3101.666667,877.666667
2405,2020-12-03,15:00,Premier League,Matchweek 6,Sat,Away,W,5,0,Cardiff City,...,353.333333,277.000000,68.000000,87.800000,93.200000,90.100000,73.666667,10504.000000,3099.333333,869.000000
2406,2020-12-06,15:00,Premier League,Matchweek 7,Sat,Home,W,2,0,Brighton,...,378.666667,303.000000,72.000000,88.833333,93.633333,90.566667,74.166667,11430.333333,3213.333333,915.333333
2407,2020-12-10,15:00,Premier League,Matchweek 9,Sat,Home,W,5,0,Burnley,...,399.333333,312.000000,68.666667,89.700000,94.966667,90.033333,72.266667,11724.333333,3124.666667,944.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2023-08-30,20:00,Premier League,Matchweek 32,Wed,Away,D,1,1,Brighton,...,298.000000,252.666667,75.333333,83.966667,91.166667,87.366667,60.666667,9223.333333,2740.666667,756.666667
80,2023-08-30,12:30,Premier League,Matchweek 29,Sat,Home,W,4,1,Liverpool,...,299.333333,254.333333,71.000000,84.800000,91.400000,87.433333,64.966667,9269.666667,2860.333333,753.333333
86,2023-09-02,16:30,Premier League,Matchweek 38,Sun,Away,L,0,1,Brentford,...,330.000000,273.333333,66.000000,86.833333,92.233333,89.633333,66.666667,10021.666667,2971.000000,790.666667
66,2023-09-02,15:00,Premier League,Matchweek 10,Sat,Home,W,4,0,Southampton,...,342.666667,257.000000,64.000000,89.033333,93.766667,92.366667,68.800000,9955.333333,2933.666667,778.000000
71,2023-09-03,20:00,Premier League,Matchweek 17,Wed,Away,W,3,1,Leeds United,...,283.666667,269.000000,68.000000,86.200000,92.833333,88.333333,65.566667,9466.666667,2761.666667,727.666667

In [205]:
matches_rolling = merged_df.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [206]:
matches_rolling

                                   date   time            comp         round  \
team
Arsenal                 1999 2020-09-24  20:00  Premier League   Matchweek 7
                        2534 2020-09-24  20:00  Premier League   Matchweek 9
                        2000 2020-09-27  14:00  Premier League   Matchweek 8
                        2535 2020-09-28  17:30  Premier League  Matchweek 11
                        2001 2020-09-30  20:00  Premier League   Matchweek 9
...                                 ...    ...             ...           ...
Wolverhampton Wanderers 443  2023-04-08  16:30  Premier League  Matchweek 38
                        43   2023-08-12  15:00  Premier League   Matchweek 3
                        44   2023-08-20  14:00  Premier League   Matchweek 4
                        41   2023-08-30  20:00  Premier League   Matchweek 1
                        42   2023-09-02  15:00  Premier League   Matchweek 2

                              day venue result   gf   ga        opponent  ...  \
team                                                                      ...
Arsenal                 1999  Mon  Away      D    1    1  Manchester Utd  ...
                        2534  Mon  Home      W    3    1  Leicester City  ...
                        2000  Sun  Home      W    1    0     Bournemouth  ...
                        2535  Sat  Home      D    1    1       Liverpool  ...
                        2001  Mon  Away      L    0    1   Sheffield Utd  ...
...                           ...   ...    ...  ...  ...             ...  ...
Wolverhampton Wanderers 443   Sun  Away      L    0    5         Arsenal  ...
                        43    Sat  Away      W  1.0  0.0         Everton  ...
                        44    Sun  Away      L  2.0  3.0  Crystal Palace  ...
                        41    Mon  Away      L  0.0  1.0  Manchester Utd  ...
                        42    Sat  Home      L  1.0  4.0        Brighton  ...

                              att.1_rolling  att.2_rolling  att.3_rolling  \
team
Arsenal                 1999     253.333333     206.666667      76.666667
                        2534     213.666667     187.666667      74.000000
                        2000     261.333333     208.000000      68.000000
                        2535     244.333333     196.333333      77.000000
                        2001     289.000000     230.000000      75.666667
...                                     ...            ...            ...
Wolverhampton Wanderers 443      171.666667     164.666667      76.000000
                        43       195.333333     200.000000      72.666667
                        44       209.333333     194.000000      69.333333
                        41       228.000000     200.000000      69.000000
                        42       245.666667     182.000000      69.000000

                              cmp%_rolling cmp%.1_rolling cmp%.2_rolling  \
team
Arsenal                 1999     80.133333      88.200000      86.300000
                        2534     78.366667      87.633333      85.033333
                        2000     79.433333      87.666667      83.900000
                        2535     77.533333      87.900000      84.266667
                        2001     80.633333      89.433333      85.866667
...                                    ...            ...            ...
Wolverhampton Wanderers 443      75.833333      86.500000      83.166667
                        43       80.933333      90.966667      85.633333
                        44       82.566667      92.166667      86.600000
                        41       83.733333      92.933333      88.933333
                        42       81.400000      90.666667      86.833333

                             cmp%.3_rolling totdist_rolling prgdist_rolling  \
team
Arsenal                 1999      55.133333     7655.666667     2731.000000
                        2534      56.366667     7000.333333     2501.333333
                        2000      58.700000     7648.000000     2753.666667
                        2535      55.900000     7425.000000     2500.666667
                        2001      60.066667     8592.333333     2816.333333
...                                     ...             ...             ...
Wolverhampton Wanderers 443       48.300000     5974.333333     2004.000000
                        43        53.000000     7052.333333     2338.666667
                        44        53.600000     7019.333333     2458.333333
                        41        50.300000     7304.333333     2448.333333
                        42        49.700000     6941.666667     2511.333333

                              touches_rolling
team
Arsenal                 1999       683.333333
                        2534       627.333333
                        2000       680.666667
                        2535       665.333333
                        2001       744.333333
...                                       ...
Wolverhampton Wanderers 443        537.000000
                        43         590.333333
                        44         595.666667
                        41         621.666667
                        42         648.666667

[2650 rows x 123 columns]

In [207]:
matches_rolling = matches_rolling.droplevel("team")

In [208]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,att.1_rolling,att.2_rolling,att.3_rolling,cmp%_rolling,cmp%.1_rolling,cmp%.2_rolling,cmp%.3_rolling,totdist_rolling,prgdist_rolling,touches_rolling
1999,2020-09-24,20:00,Premier League,Matchweek 7,Mon,Away,D,1,1,Manchester Utd,...,253.333333,206.666667,76.666667,80.133333,88.200000,86.300000,55.133333,7655.666667,2731.000000,683.333333
2534,2020-09-24,20:00,Premier League,Matchweek 9,Mon,Home,W,3,1,Leicester City,...,213.666667,187.666667,74.000000,78.366667,87.633333,85.033333,56.366667,7000.333333,2501.333333,627.333333
2000,2020-09-27,14:00,Premier League,Matchweek 8,Sun,Home,W,1,0,Bournemouth,...,261.333333,208.000000,68.000000,79.433333,87.666667,83.900000,58.700000,7648.000000,2753.666667,680.666667
2535,2020-09-28,17:30,Premier League,Matchweek 11,Sat,Home,D,1,1,Liverpool,...,244.333333,196.333333,77.000000,77.533333,87.900000,84.266667,55.900000,7425.000000,2500.666667,665.333333
2001,2020-09-30,20:00,Premier League,Matchweek 9,Mon,Away,L,0,1,Sheffield Utd,...,289.000000,230.000000,75.666667,80.633333,89.433333,85.866667,60.066667,8592.333333,2816.333333,744.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,2023-04-08,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,171.666667,164.666667,76.000000,75.833333,86.500000,83.166667,48.300000,5974.333333,2004.000000,537.000000
43,2023-08-12,15:00,Premier League,Matchweek 3,Sat,Away,W,1.0,0.0,Everton,...,195.333333,200.000000,72.666667,80.933333,90.966667,85.633333,53.000000,7052.333333,2338.666667,590.333333
44,2023-08-20,14:00,Premier League,Matchweek 4,Sun,Away,L,2.0,3.0,Crystal Palace,...,209.333333,194.000000,69.333333,82.566667,92.166667,86.600000,53.600000,7019.333333,2458.333333,595.666667
41,2023-08-30,20:00,Premier League,Matchweek 1,Mon,Away,L,0.0,1.0,Manchester Utd,...,228.000000,200.000000,69.000000,83.733333,92.933333,88.933333,50.300000,7304.333333,2448.333333,621.666667
42,2023-09-02,15:00,Premier League,Matchweek 2,Sat,Home,L,1.0,4.0,Brighton,...,245.666667,182.000000,69.000000,81.400000,90.666667,86.833333,49.700000,6941.666667,2511.333333,648.666667

In [209]:
matches_rolling.index = range(matches_rolling.shape[0])

In [210]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,att.1_rolling,att.2_rolling,att.3_rolling,cmp%_rolling,cmp%.1_rolling,cmp%.2_rolling,cmp%.3_rolling,totdist_rolling,prgdist_rolling,touches_rolling
0,2020-09-24,20:00,Premier League,Matchweek 7,Mon,Away,D,1,1,Manchester Utd,...,253.333333,206.666667,76.666667,80.133333,88.200000,86.300000,55.133333,7655.666667,2731.000000,683.333333
1,2020-09-24,20:00,Premier League,Matchweek 9,Mon,Home,W,3,1,Leicester City,...,213.666667,187.666667,74.000000,78.366667,87.633333,85.033333,56.366667,7000.333333,2501.333333,627.333333
2,2020-09-27,14:00,Premier League,Matchweek 8,Sun,Home,W,1,0,Bournemouth,...,261.333333,208.000000,68.000000,79.433333,87.666667,83.900000,58.700000,7648.000000,2753.666667,680.666667
3,2020-09-28,17:30,Premier League,Matchweek 11,Sat,Home,D,1,1,Liverpool,...,244.333333,196.333333,77.000000,77.533333,87.900000,84.266667,55.900000,7425.000000,2500.666667,665.333333
4,2020-09-30,20:00,Premier League,Matchweek 9,Mon,Away,L,0,1,Sheffield Utd,...,289.000000,230.000000,75.666667,80.633333,89.433333,85.866667,60.066667,8592.333333,2816.333333,744.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2645,2023-04-08,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,171.666667,164.666667,76.000000,75.833333,86.500000,83.166667,48.300000,5974.333333,2004.000000,537.000000
2646,2023-08-12,15:00,Premier League,Matchweek 3,Sat,Away,W,1.0,0.0,Everton,...,195.333333,200.000000,72.666667,80.933333,90.966667,85.633333,53.000000,7052.333333,2338.666667,590.333333
2647,2023-08-20,14:00,Premier League,Matchweek 4,Sun,Away,L,2.0,3.0,Crystal Palace,...,209.333333,194.000000,69.333333,82.566667,92.166667,86.600000,53.600000,7019.333333,2458.333333,595.666667
2648,2023-08-30,20:00,Premier League,Matchweek 1,Mon,Away,L,0.0,1.0,Manchester Utd,...,228.000000,200.000000,69.000000,83.733333,92.933333,88.933333,50.300000,7304.333333,2448.333333,621.666667
2649,2023-09-02,15:00,Premier League,Matchweek 2,Sat,Home,L,1.0,4.0,Brighton,...,245.666667,182.000000,69.000000,81.400000,90.666667,86.833333,49.700000,6941.666667,2511.333333,648.666667

In [217]:
matches_rolling.to_csv("cleaned.csv")